#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Author     : Hongzhuo Liang 
# E-mail     : liang@informatik.uni-hamburg.de
# Description: 
# Date       : 20/11/2020: 08:37
# File Name  : generate_urdf
import sys
import json
import os
from termcolor import cprint


def generate_urdf(robot_name, MESH_PATH, scale_factor="1.0"):
    output_file = open("./urdf/"+robot_name+".urdf", "wt")
    input_file = open("template.urdf", "rt")
    for line in input_file:
        line = line.replace("ROBOT_NAME", robot_name)
        line = line.replace("MESH_PATH", MESH_PATH)
        line = line.replace("SCALE_FACTOR", scale_factor)
        output_file.write(line)
    output_file.write("<!--This file is automaticlly generated, use it only if you generated by the script!--> \n")
    output_file.write("<!--The script name is generate_urdf.py--> \n")
    output_file.write("\n")
    output_file.close()
    input_file.close()
    cprint("generate {}.urdf finished".format(robot_name), "green")


def main():
    # Grab all the object information
    os.makedirs("./urdf", exist_ok=True)
    with open("objects.json", "r") as handle:
        objects = json.load(handle)["objects"]
    for obj in objects:
        obj_path = "./models/ycb/{}/google_16k/nontextured.ply".format(obj)
        obj_path = os.path.abspath(obj_path)
        if os.path.isfile(obj_path):
            generate_urdf(obj, obj_path)
        else:
            cprint("warning, {} not exist".format(obj_path), "yellow")


if __name__ == "__main__":
    main()

